/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gorail;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.json.JSONException;
import org.json.JSONObject;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.http.HttpHost;

//import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.params.HttpConnectionParams;
import org.apache.http.params.HttpParams;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author JAYANT RASTOGI
 */
public class Gorail1 extends javax.swing.JFrame {

    /**
     * Creates new form Gorail1
     */
    public Gorail1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        src = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        dest = new javax.swing.JTextField();
        Date1 = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trainbetween = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        trainno2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        src2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        age2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        dest2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        quota2 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        trainbetween2 = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        trainno1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        src1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dest1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Date2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        classcode = new javax.swing.JComboBox<>();
        quota = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        trainbetween1 = new javax.swing.JTable();
        bookbutton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        trainno = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        LiveStatusTable = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnr = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GORAIL");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setLayout(null);

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("TRAIN BETWEEN STATIONS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(0, 0, 822, 32);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("SOURCE.");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(218, 43, 119, 33);
        jPanel4.add(src);
        src.setBounds(371, 44, 144, 33);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("DESTINATION.");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(218, 82, 119, 37);

        jButton6.setBackground(new java.awt.Color(102, 0, 0));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/submit1.png"))); // NOI18N
        jButton6.setText("SUBMIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(388, 176, 135, 36);

        dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destActionPerformed(evt);
            }
        });
        jPanel4.add(dest);
        dest.setBounds(371, 83, 144, 33);

        Date1.setDateFormatString("dd-MM");
        jPanel4.add(Date1);
        Date1.setBounds(371, 122, 144, 32);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("DATE");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(218, 125, 119, 33);

        trainbetween.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train no.", "Train name", "Source", "Departure", "Destination", "Arrival", "M", "T", "W", "T", "F", "S", "S", "2S", "CC", "2A", "FC", "1A", "3E", "3A", "SL"
            }
        ));
        jScrollPane1.setViewportView(trainbetween);
        if (trainbetween.getColumnModel().getColumnCount() > 0) {
            trainbetween.getColumnModel().getColumn(6).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(6).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(7).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(7).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(8).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(8).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(9).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(9).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(10).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(10).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(11).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(11).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(12).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(12).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(13).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(13).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(14).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(14).setPreferredWidth(28);
            trainbetween.getColumnModel().getColumn(15).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(15).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(16).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(16).setPreferredWidth(28);
            trainbetween.getColumnModel().getColumn(17).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(17).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(18).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(18).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(19).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(19).setPreferredWidth(25);
            trainbetween.getColumnModel().getColumn(20).setMinWidth(25);
            trainbetween.getColumnModel().getColumn(20).setPreferredWidth(25);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 248, 812, 175);

        jLabel20.setBackground(new java.awt.Color(153, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("             CLASSES");
        jLabel20.setOpaque(true);
        jPanel4.add(jLabel20);
        jLabel20.setBounds(614, 225, 198, 17);

        jLabel21.setBackground(new java.awt.Color(153, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("      DAYS  RUNNING");
        jLabel21.setOpaque(true);
        jPanel4.add(jLabel21);
        jLabel21.setBounds(432, 225, 176, 17);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/bk3.jpg"))); // NOI18N
        jPanel4.add(jLabel50);
        jLabel50.setBounds(0, 34, 820, 460);

        jTabbedPane1.addTab("Train Between Stations", jPanel4);

        jPanel6.setLayout(null);

        jButton9.setBackground(new java.awt.Color(102, 0, 0));
        jButton9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("FARE ENQUIRY");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(0, 0, 822, 32);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("TRAIN NO.");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(89, 51, 79, 33);

        trainno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainno2ActionPerformed(evt);
            }
        });
        jPanel6.add(trainno2);
        trainno2.setBounds(178, 52, 144, 33);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("SOURCE");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(95, 97, 73, 33);

        src2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                src2ActionPerformed(evt);
            }
        });
        jPanel6.add(src2);
        src2.setBounds(178, 98, 144, 33);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("      AGE");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(95, 144, 53, 33);

        age2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age2ActionPerformed(evt);
            }
        });
        jPanel6.add(age2);
        age2.setBounds(178, 145, 144, 33);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("DATE.");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(367, 51, 73, 33);

        jDateChooser3.setDateFormatString("dd-MM-YYYY");
        jPanel6.add(jDateChooser3);
        jDateChooser3.setBounds(484, 50, 144, 35);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("DESTINATION");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(367, 97, 107, 33);

        dest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dest2ActionPerformed(evt);
            }
        });
        jPanel6.add(dest2);
        dest2.setBounds(484, 98, 144, 33);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("QUOTA CODE");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(367, 144, 107, 33);

        jButton10.setBackground(new java.awt.Color(102, 0, 0));
        jButton10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/submit1.png"))); // NOI18N
        jButton10.setText("SUBMIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(305, 196, 152, 32);

        quota2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quota2.setMaximumRowCount(5);
        quota2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GN", "LD", "HO", "DF", "PH", "FT", "DP", "CK", "PT", "SS", "HP", "RE", "GNRS", "OS", "PQ", "RC(RAC)", "RS", "YU", "LB" }));
        jPanel6.add(quota2);
        quota2.setBounds(484, 142, 144, 34);

        trainbetween2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train no.", "Train name", "Source", "Destination", "Fare", "Class Code", "Class Name"
            }
        ));
        jScrollPane5.setViewportView(trainbetween2);
        if (trainbetween2.getColumnModel().getColumnCount() > 0) {
            trainbetween2.getColumnModel().getColumn(2).setMinWidth(30);
            trainbetween2.getColumnModel().getColumn(2).setPreferredWidth(30);
            trainbetween2.getColumnModel().getColumn(3).setMinWidth(30);
            trainbetween2.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel6.add(jScrollPane5);
        jScrollPane5.setBounds(10, 268, 802, 151);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/bk3.jpg"))); // NOI18N
        jPanel6.add(jLabel51);
        jLabel51.setBounds(0, 34, 820, 460);

        jTabbedPane1.addTab("Fare Enquiry", jPanel6);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 48, 62, 22));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("TRAIN NO.");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 48, 96, 33));

        trainno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainno1ActionPerformed(evt);
            }
        });
        jPanel5.add(trainno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 49, 144, 33));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("DESTINATION");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 93, 107, 33));

        src1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                src1ActionPerformed(evt);
            }
        });
        jPanel5.add(src1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 94, 144, 33));

        jButton7.setBackground(new java.awt.Color(102, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SEAT AVAILABILITY");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 812, 32));

        jButton8.setBackground(new java.awt.Color(102, 0, 0));
        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/submit1.png"))); // NOI18N
        jButton8.setText("SUBMIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 199, 145, 32));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("SOURCE");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 93, 73, 33));

        dest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dest1ActionPerformed(evt);
            }
        });
        jPanel5.add(dest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 94, 154, 33));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("CLASS CODE.");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 140, -1, 33));

        Date2.setDateFormatString("dd-MM-yyyy");
        jPanel5.add(Date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 48, 154, 35));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("DATE.");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 48, 73, 33));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("QUOTA CODE");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 140, 107, 33));

        classcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classcode.setMaximumRowCount(5
        );
        classcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SL", "2S", "CC", "2A", "FC", "1A", "3E", "3A" }));
        jPanel5.add(classcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 138, 144, 34));

        quota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quota.setMaximumRowCount(5);
        quota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GN", "LD", "HO", "DF", "PH", "FT", "DP", "CK", "PT", "SS", "HP", "RE", "GNRS", "OS", "PQ", "RC(RAC)", "RS", "YU", "LB" }));
        jPanel5.add(quota, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 138, 205, 34));

        trainbetween1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train no.", "Train name", "Source", "Destination", "Class Name", "Class Code", "Date", "Status"
            }
        ));
        jScrollPane4.setViewportView(trainbetween1);
        if (trainbetween1.getColumnModel().getColumnCount() > 0) {
            trainbetween1.getColumnModel().getColumn(2).setMinWidth(30);
            trainbetween1.getColumnModel().getColumn(2).setPreferredWidth(30);
            trainbetween1.getColumnModel().getColumn(3).setMinWidth(30);
            trainbetween1.getColumnModel().getColumn(3).setPreferredWidth(30);
            trainbetween1.getColumnModel().getColumn(4).setHeaderValue("Class Name");
            trainbetween1.getColumnModel().getColumn(5).setMinWidth(30);
            trainbetween1.getColumnModel().getColumn(5).setPreferredWidth(30);
            trainbetween1.getColumnModel().getColumn(5).setHeaderValue("Class Code");
        }

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 802, 151));

        bookbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/Add-ticket-icon.png"))); // NOI18N
        bookbutton.setText("BOOK TICKET");
        bookbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookbuttonMouseClicked(evt);
            }
        });
        bookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbuttonActionPerformed(evt);
            }
        });
        jPanel5.add(bookbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 404, 243, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText(" Select train from the table to book ticket");
        jLabel28.setOpaque(true);
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 467, 240, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/bk3.jpg"))); // NOI18N
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, 470));

        jTabbedPane1.addTab("Seat Availability", jPanel5);

        jPanel2.setLayout(null);

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LIVE TRAIN STATUS");
        jPanel2.add(jButton3);
        jButton3.setBounds(0, 0, 822, 32);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("    TRAIN NO.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(251, 50, 135, 33);
        jPanel2.add(trainno);
        trainno.setBounds(415, 51, 144, 33);

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/submit1.png"))); // NOI18N
        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(341, 141, 153, 32);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("      DATE.");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(251, 90, 135, 33);

        date.setDateFormatString("yyyyMMdd");
        jPanel2.add(date);
        date.setBounds(415, 90, 144, 33);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        LiveStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Station ", "Sch. Arrival", "Sch. Departure", "Act. Arrival / Departure", "Status"
            }
        ));
        LiveStatusTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(LiveStatusTable);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 202, 802, 176);

        jLabel54.setBackground(new java.awt.Color(102, 0, 0));
        jLabel54.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("POSITION :");
        jLabel54.setOpaque(true);
        jPanel2.add(jLabel54);
        jLabel54.setBounds(10, 390, 100, 40);

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel55.setOpaque(true);
        jPanel2.add(jLabel55);
        jLabel55.setBounds(140, 390, 670, 40);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/bk3.jpg"))); // NOI18N
        jLabel48.setText("jLabel48");
        jPanel2.add(jLabel48);
        jLabel48.setBounds(0, 34, 820, 460);

        jTabbedPane1.addTab("Live Train Status", jPanel2);

        jPanel3.setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CHECK PNR STATUS");
        jPanel3.add(jButton1);
        jButton1.setBounds(0, 0, 822, 32);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ENTER PNR NO.");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(151, 44, 135, 33);

        pnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnrActionPerformed(evt);
            }
        });
        jPanel3.add(pnr);
        pnr.setBounds(304, 45, 144, 33);

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/submit1.png"))); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(493, 43, 148, 34);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Train Name:");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(151, 167, 140, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("Train Number:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(151, 125, 140, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("From:");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(151, 249, 140, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("To:");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(151, 208, 140, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Booking Status:");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(151, 285, 140, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Class :");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(151, 399, 140, 22);

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Current Status:");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(151, 321, 140, 31);

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Date of Journey:");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(151, 363, 140, 25);

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Total Passengers:");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(151, 427, 140, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 51));
        jLabel32.setText("PNR:");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(151, 84, 140, 30);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel35.setOpaque(true);
        jPanel3.add(jLabel35);
        jLabel35.setBounds(309, 167, 282, 30);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel36.setOpaque(true);
        jPanel3.add(jLabel36);
        jLabel36.setBounds(309, 208, 220, 30);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel37.setOpaque(true);
        jPanel3.add(jLabel37);
        jLabel37.setBounds(309, 249, 221, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jPanel3.add(jLabel38);
        jLabel38.setBounds(597, 290, 140, 30);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel40.setOpaque(true);
        jPanel3.add(jLabel40);
        jLabel40.setBounds(309, 358, 170, 30);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel41.setOpaque(true);
        jPanel3.add(jLabel41);
        jLabel41.setBounds(310, 400, 170, 22);

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel42.setOpaque(true);
        jPanel3.add(jLabel42);
        jLabel42.setBounds(310, 430, 170, 20);

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel43.setOpaque(true);
        jPanel3.add(jLabel43);
        jLabel43.setBounds(305, 84, 166, 30);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel44.setOpaque(true);
        jPanel3.add(jLabel44);
        jLabel44.setBounds(309, 321, 170, 30);

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel45.setOpaque(true);
        jPanel3.add(jLabel45);
        jLabel45.setBounds(305, 125, 166, 30);

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel46.setOpaque(true);
        jPanel3.add(jLabel46);
        jLabel46.setBounds(309, 287, 174, 28);

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Chart Prepared");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(150, 460, 140, 30);

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel47.setOpaque(true);
        jPanel3.add(jLabel47);
        jLabel47.setBounds(310, 460, 170, 20);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/bk3.jpg"))); // NOI18N
        jPanel3.add(jLabel49);
        jLabel49.setBounds(0, 34, 820, 460);

        jTabbedPane1.addTab("PNR Status", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setBackground(new java.awt.Color(153, 0, 0));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("       GORAIL ");
        jLabel34.setOpaque(true);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/logo.png"))); // NOI18N

        jButton11.setBackground(new java.awt.Color(102, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("WELCOME TO GORAIL WINDOW");

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorail/logout.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel53.setBackground(new java.awt.Color(153, 0, 0));
        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText(" LOGOUT");
        jLabel53.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnrActionPerformed
           




        // TODO add your handling code here:
    }//GEN-LAST:event_pnrActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void trainno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainno2ActionPerformed

    private void src2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_src2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_src2ActionPerformed

    private void age2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age2ActionPerformed

    private void dest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dest2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String pn = pnr.getText();
        String s="http://api.railwayapi.com/pnr_status/pnr/"+pn+"/apikey/zxnpmy9q/";
        System.out.println(s);
        sQuery obj=new sQuery();
        String respo2 = obj.getQuestionsUsingUnirest(s);
        System.out.println(respo2);
        JSONObject myjson2;
        try 
        {
            myjson2 = new JSONObject(respo2);
            String from = myjson2.getJSONObject("from_station").getString("name");
            String to = myjson2.getJSONObject("reservation_upto").getString("name");
            String tname = myjson2.getString("train_name");
            String clas = myjson2.getString("class");
            //String tpassenger = myjson2.getInt("total_passengers").toString();
            String doj = myjson2.getString("doj");
            String tno = myjson2.getString("train_num");
            String pnrr = myjson2.getString("pnr");
            String bookS = myjson2.getJSONArray("passengers").getJSONObject(0).getString("booking_status");
            String curS = myjson2.getJSONArray("passengers").getJSONObject(0).getString("current_status");
            String cp = myjson2.getString("chart_prepared");
            jLabel43.setText(pnrr);jLabel45.setText(tno);jLabel35.setText(tname);
            jLabel36.setText(to);jLabel37.setText(from);jLabel46.setText(bookS);
            jLabel44.setText(curS);jLabel40.setText(doj);jLabel41.setText(clas);
            jLabel42.setText("1"); 
            jLabel47.setText(cp);
            pnr.setText("");
            
        } 
        catch (JSONException e) {
           JOptionPane.showMessageDialog( null , e);
        }


        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        RetStaCode ob = new RetStaCode();
        String fr = ob.stationcode(src.getText());
        String to = ob.stationcode(dest.getText());
        String dte = (( JTextField ) Date1.getDateEditor().getUiComponent()).getText();
        System.out.println(fr + " " + to + " " + dte );
        
        String s="http://api.railwayapi.com/between/source/"+fr+"/dest/"+to+"/date/"+dte+"/apikey/zxnpmy9q/";
       //System.out.println(s);
       sQuery obj=new sQuery();
       String respo = obj.getQuestionsUsingUnirest(s);
       System.out.println(respo);
       JSONObject myjson;
        try 
        {
            myjson = new JSONObject(respo);
            JSONArray jarr = myjson.getJSONArray("train");
            int l = jarr.length();
            for(int i=0;i<l;i++){
                    //  String m = jarr.getJSONObject(i).getJSONObject("station_").getString("name");
                      JSONObject jo = jarr.getJSONObject(i);
                      String m1 =jo.getString("number");
                      String m2= jo.getString("name");
                      String m3= jo.getString("src_departure_time");
                      String m4= jo.getString("dest_arrival_time");
                      JSONArray d = jo.getJSONArray("days");
                      String[] day = new String[7];
                      for(int j = 0 ; j< 7 ; j++){
                          day[j]=d.getJSONObject(j).getString("runs");
                      }
                      JSONArray c = jo.getJSONArray("classes");
                      
                      String[] clas = new String[8];
                      for(int j = 0 ; j< 8 ; j++){
                          clas[j]=c.getJSONObject(j).getString("available");
                      }
                      DefaultTableModel model = ( DefaultTableModel )trainbetween.getModel();
                      model.addRow(new Object[] {m1,m2,fr,m3,to,m4, day[0],day[1],day[2],day[3],day[4],day[5],day[6], clas[0],clas[1],clas[2],clas[3],clas[4],clas[5],clas[6],clas[7] });
                }
            
        } 
        catch (JSONException e) {
           JOptionPane.showMessageDialog( null , e);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String dte = (( JTextField ) date.getDateEditor().getUiComponent()).getText();
       String tno = trainno.getText();
       System.out.println(dte+"hello");
       System.out.println(tno);
       String s="http://api.railwayapi.com/live/train/"+tno+"/doj/"+dte+"/apikey/zxnpmy9q/";
       //System.out.println(s);
       sQuery obj=new sQuery();
       String respo = obj.getQuestionsUsingUnirest(s);
       System.out.println(respo);
       JSONObject myjson;
        try 
        {
            myjson = new JSONObject(respo);
            JSONArray jarr = myjson.getJSONArray("route");
            int l = jarr.length();
            if(l!=0){
                for(int i=0;i<l;i++){
                    String m = jarr.getJSONObject(i).getJSONObject("station_").getString("name");
                     String m1 = jarr.getJSONObject(i).getString("scharr");
                      String m2= jarr.getJSONObject(i).getString("schdep");
                      String m3= jarr.getJSONObject(i).getString("actarr");
                      String m4= jarr.getJSONObject(i).getString("actdep");
                      m3=m3.concat(" / ");
                      m3=m3.concat(m4);
                      String m5= jarr.getJSONObject(i).getString("status");
                      DefaultTableModel model = ( DefaultTableModel )LiveStatusTable.getModel();
                      model.addRow(new Object[] { m , m1 ,m2 , m3 , m5 });
                }
               
            }
            String pos = myjson.getString("position");
            jLabel55.setText(pos);
            
            /*
            String jsonObj22 = myjson.getString("train_number");
            String jsonObj23 = myjson.getString("position");
            JSONObject jsonObj1 = myjson.getJSONObject("current_station");
            //JSONArray jsonObj2 = jsonObj1.getJSONArray("entry");
            String jsonObj24 = jsonObj1.getString("actdep");
            
            JSONObject jsonObj2 = jsonObj1.getJSONObject("station_");
            //JSONObject jsonObj3 = jsonObj2.getJSONObject(0);
            String jsonObj3 = jsonObj2.getString("code");
           // System.out.println(jsonObj3.getJSONObject("content"));
           // System.out.println("here ===>>>"+jsonObj3.getJSONObject("content").get("$t").toString());
              System.out.println("TRAIN NUMBER "   +   "       POSITION "  + "                               ACTUAL DEPARTURE "  + " STATION CODE ");
              System.out.println(jsonObj22 + "         " +  jsonObj23 + "  " + jsonObj24 + "  " + jsonObj3 );
            */
            
        } 
        catch (JSONException e) {
           JOptionPane.showMessageDialog( null , e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        RetStaCode ob = new RetStaCode();
        String trno = trainno2.getText();
         String age = age2.getText();
        String quot  = quota2.getSelectedItem().toString();
        String from = ob.stationcode(src2.getText());
        String too = ob.stationcode(dest2.getText());
        String dte = (( JTextField ) jDateChooser3.getDateEditor().getUiComponent()).getText();
        System.out.println(from + " " + too + " " + dte+   " " +quot  + " " + trno );
        String s="http://api.railwayapi.com/fare/train/"+trno+"/source/"+from+"/dest/"+too+"/age/"+age+"/quota/"+quot+"/doj/"+dte+"/apikey/zxnpmy9q/";
        System.out.println(s);
        sQuery obj2=new sQuery();
        String respo2 = obj2.getQuestionsUsingUnirest(s);
        System.out.println(respo2);
        JSONObject myjson2;
        try 
        {
            myjson2 = new JSONObject(respo2);
            JSONArray jarr2 = myjson2.getJSONArray("fare");
             String trainname2 = myjson2.getJSONObject("train").getString("name");
            int l = jarr2.length();
            for(int i=0;i<l;i++){
                    //  String m = jarr.getJSONObject(i).getJSONObject("station_").getString("name");
                      JSONObject jo2 = jarr2.getJSONObject(i);
                      String m1 =jo2.getString("fare");
                      String m2= jo2.getString("code");
                      String m3 =jo2.getString("name");
                      DefaultTableModel model = ( DefaultTableModel )trainbetween2.getModel();
                      model.addRow(new Object[] {trno,trainname2,from,too,m1,m2,m3 });
                }
            
        } 
        catch (JSONException e) {
           JOptionPane.showMessageDialog( null , e);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void bookbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookbuttonMouseClicked
        DefaultTableModel model=(DefaultTableModel)trainbetween1.getModel();
        int rowindex = trainbetween1.getSelectedRow();

        String trno = model.getValueAt(rowindex, 0).toString();
        String trname = model.getValueAt(rowindex, 1).toString();
        String sorc = model.getValueAt(rowindex, 2).toString();
        String dst = model.getValueAt(rowindex, 3).toString();
        String clsnme = model.getValueAt(rowindex, 4).toString();
        String clscde = model.getValueAt(rowindex, 5).toString();
        String dt = model.getValueAt(rowindex, 6).toString();
        String status = model.getValueAt(rowindex, 7).toString();
        book frame1=new book();
        frame1.bookfunc(trno,trname,sorc,dst,clsnme,clscde,dt,status);
        this.dispose();
        frame1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_bookbuttonMouseClicked

    private void dest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dest1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        RetStaCode ob = new RetStaCode();
        String trno = trainno1.getText();
        String ccode = classcode.getSelectedItem().toString();
        String quot  = quota.getSelectedItem().toString();
        String from = ob.stationcode(src1.getText());
        String too = ob.stationcode(dest1.getText());

        String date = (( JTextField ) Date2.getDateEditor().getUiComponent()).getText();
        System.out.println(from + " " + too + " " + date+   " " +quot + " " + ccode + " " + trno );

        String s="http://api.railwayapi.com/check_seat/train/"+trno+"/source/"+from+"/dest/"+too+"/date/"+date+"/class/"+ccode+"/quota/"+quot+"/apikey/zxnpmy9q/";
        System.out.println(s);
        sQuery obj1=new sQuery();
        String respo1 = obj1.getQuestionsUsingUnirest(s);
        System.out.println(respo1);
        JSONObject myjson1;
        try
        {
            myjson1 = new JSONObject(respo1);
            String trname1 = myjson1.getString("train_name");System.out.println(trname1 );
            JSONArray jarr1 = myjson1.getJSONArray("availability");
            String codename1 = myjson1.getJSONObject("class").getString("class_name");

            int l = jarr1.length();
            for(int i=0;i<l;i++){
                //  String m = jarr.getJSONObject(i).getJSONObject("station_").getString("name");
                JSONObject jo1 = jarr1.getJSONObject(i);
                String m1 =jo1.getString("date");
                String m2= jo1.getString("status");

                DefaultTableModel model = ( DefaultTableModel )trainbetween1.getModel();
                model.addRow(new Object[] {trno,trname1,from,too,codename1,ccode,m1,m2 });
            }

        }
        catch (JSONException e) {
            JOptionPane.showMessageDialog( null , e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void src1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_src1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_src1ActionPerformed

    private void trainno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainno1ActionPerformed

    private void bookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookbuttonActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.dispose();
        index id = new index();
        id.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gorail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gorail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gorail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gorail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gorail1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date1;
    private com.toedter.calendar.JDateChooser Date2;
    private javax.swing.JTable LiveStatusTable;
    private javax.swing.JTextField age2;
    private javax.swing.JButton bookbutton;
    private javax.swing.JComboBox<String> classcode;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField dest;
    private javax.swing.JTextField dest1;
    private javax.swing.JTextField dest2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pnr;
    private javax.swing.JComboBox<String> quota;
    private javax.swing.JComboBox<String> quota2;
    private javax.swing.JTextField src;
    private javax.swing.JTextField src1;
    private javax.swing.JTextField src2;
    private javax.swing.JTable trainbetween;
    private javax.swing.JTable trainbetween1;
    private javax.swing.JTable trainbetween2;
    private javax.swing.JTextField trainno;
    private javax.swing.JTextField trainno1;
    private javax.swing.JTextField trainno2;
    // End of variables declaration//GEN-END:variables
}
